### ISSUE TITLE
Installation error (colormath)

### ISSUE THREAD

**Issue by gamesbook** [jyotiska/colorweave#7]
Stacktrace:

```
pip install colorweave
Collecting colorweave
  Using cached colorweave-0.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-UL8qb5/colorweave/setup.py", line 5, in <module>
        import colorweave
      File "colorweave.py", line 9, in <module>
        from colormath.color_objects import RGBColor
    ImportError: cannot import name RGBColor

```

**Comment by jyotiska** [comment]
Can you try using colormath version 1.0.8? You can use the following `pip install colormath==1.0.8`
